# This workflow will do a clean installation of node dependencies,
# cache/restore them, build the source code and deploy it on GitHub Pages.

name: Deploy

on:
  push:
    branches: [ "master", "deploy" ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          # Use a LTS active version. Node 20 will remain supported until 2026.
          node-version: '20.x'
          cache: 'npm'
      # We must also install Quarto to build the documentation (in `docs/`)
      - name: Install Quarto
        uses: quarto-dev/quarto-actions/setup@v2
      # Install dependencies (`npm ci` is similar to `npm install`, but for
      # "clean" environments, such as CI).
      - name: Install Node dependencies
        run: npm ci
      # Build the website using Create-React-App in the `build/` folder.
      - name: Build website
        run: npm run build
      # Upload the docs as an artifact (required for deploying to Pages)
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: "build"
      # Deploy the artifact (built website) to Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
